### ISSUE TITLE
gdal_translate has PROJ issues

### ISSUE THREAD

**Issue by antonio-rodriges** [conda-forge/proj.4-feedstock#49] opened 2019-06-06 20:49 UTC
Issue:

I installed GDAL (https://anaconda.org/conda-forge/gdal) successfully many times before, but now I am getting the following errors running gdal_translate:

```
ERROR 1: PROJ: pj_obj_create: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: createGeodeticReferenceFrame: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_as_wkt: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: createGeodeticReferenceFrame: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: pj_obj_create: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_as_wkt: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_create_from_wkt: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_create_from_wkt: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: pj_obj_create: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_as_wkt: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_as_wkt: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_create_from_wkt: Open of /opt/anaconda/envs/gis/share/proj failed
ERROR 1: PROJ: proj_create_from_database: Open of /opt/anaconda/envs/gis/share/proj failed
```

I created the environment like this
`conda create -n gis -c conda-forge python=3.7 gdal nco `

**Comment by xylar** [comment] 2019-06-07 07:35
@antonio-rodriges that's pretty strange.  I wasn't able to reproduce your error:
```
conda create -n gis -c conda-forge python=3.7 gdal nco
conda activate gis
wget http://www.geos.ed.ac.uk/~smudd/export_data/WhiteadderDEM.tif
gdal_translate -of ENVI WhiteadderDEM.tif WhiteadderDEM.bil
```
I didn't see any errors.

In case it helps, here's my environment:
```
$ conda list
# packages in environment at /home/xylar/miniconda3/envs/gis:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.70.0               ha2d47e9_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cfitsio                   3.430             h0bd2449_1002    conda-forge
cftime                    1.0.3.4         py37hd352d35_1001    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
esmf                      7.1.0             h9eb252b_1005    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.0            py37hf242f0b_3    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gsl                       2.4               h294904e_1006    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgdal                   3.0.0                h02bbc0b_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.3                 h4e4e079_0    conda-forge
libspatialite             4.3.0a            h4c5cd43_1028    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             hc99cbb1_1010    conda-forge
nco                       4.8.0                hfb3d286_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf-fortran            4.4.5             hea25ff8_1000    conda-forge
netcdf4                   1.5.1.2          py37had58050_0    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hbeee2d4_0    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tempest-remap             2.0.3                h5f743cb_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

Can you confirm that the directory `/opt/anaconda/envs/gis/share/proj` either doesn't exist or has some other kind of permission issues?

**Comment by ocefpaf** [comment] 2019-06-07 12:02
@antonio-rodriges please fill the required information in the issue template. We cannot debug the problem without it.

**Comment by antonio-rodriges** [comment] 2019-06-07 19:53
Sorry, here are the details:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/anaconda/envs/gis:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.70.0               ha2d47e9_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.5.15                     0
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2019.3.9                 py37_0
cfitsio                   3.430             h0bd2449_1002    conda-forge
cftime                    1.0.3.4         py37hd352d35_1001    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
esmf                      7.1.0             h9eb252b_1005    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.0            py37hf242f0b_3    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.5.1                h560c3f3_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gsl                       2.4               h294904e_1006    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1
libgdal                   3.0.0                h02bbc0b_3    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.3                 h4e4e079_0    conda-forge
libspatialite             4.3.0a            h4c5cd43_1028    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             hc99cbb1_1010    conda-forge
nco                       4.8.0                hfb3d286_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf-fortran            4.4.5             hea25ff8_1000    conda-forge
netcdf4                   1.5.1.2          py37had58050_0    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1c               h7b6447c_1
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hbeee2d4_0    conda-forge
proj4                     6.1.0                he751ad9_2    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tempest-remap             2.0.3                h5f743cb_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

 active environment : gis
    active env location : /opt/anaconda/envs/gis
            shell level : 1
       user config file : /home/chronos/.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /opt/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /home/chronos/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /home/chronos/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-1045-azure ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


```
</details>

The directory `/opt/anaconda/envs/gis/share/proj` exists and permissions are fine.

However, it works as expected when I run `source /opt/anaconda/bin/activate gis` before calling `gdal_translate`. Previous versions of `conda` did not behave like this. I have a software which calls `gdal_translate` and other `gdal` tools automatically. Now after updating `conda` the software got broken. It may be possible to wrap a call to `gdal_translate` within a script that calls `source...` first. However, this  may introduce an overhead.

Is there a way to run a `gdal` tool installed by new `conda` version without calling `source /opt/anaconda/bin/activate gis` before?

**Comment by ocefpaf** [comment] 2019-06-07 20:01
> The directory `/opt/anaconda/envs/gis/share/proj` exists and permissions are fine.
> 
> However, it works as expected when I run `source /opt/anaconda/bin/activate gis` before calling `gdal_translate`. Previous versions of `conda` did not behave like this. I have a software which calls `gdal_translate` and other `gdal` tools automatically. Now after updating `conda` the software got broken. It may be possible to wrap a call to `gdal_translate` within a script that calls `source...` first. However, this may introduce an overhead.
> 
> Is there a way to run a `gdal` tool installed by new `conda` version without calling `source /opt/anaconda/bin/activate gis` before?

You have to activate your env before using the packages in that `env`, otherwise they are not even in the path and you could be calling another `gdal` installation. However, with latest conda only `conda activate gis` should do it. No need for `source /opt/anaconda/bin/activate gis`, unless you have multiple installations of conda and writing the full patch is necessary.

Closing this b/c there is nothing wrong with the package. Looks like a `conda` usage question. We can still help you here but b/c this is not actionable I won't leave it open to spare the feedstock maintainers.

**Closed as completed by ocefpaf** 2019-06-07 20:01 UTC

**Comment by xylar** [comment] 2019-06-07 20:04
@antonio-rodriges, I was about to suggest the same as @ocefpaf.  For a little more background, if you don't call `conda activate gis`, there is an environment variable, required by `proj.4` that doesn't get set.  A hack you can use if you really need to try to use the environment without activating it is to set the `PROJ_LIB` environment variable manually.  I've done this in some of my projects.  But you're setting yourself for a world of hurt in the future if any more environment variables get defined and you have to keep chasing them.  I strongly recommend figuring out how to work `conda activate ...` into your workflow somehow.

**Comment by antonio-rodriges** [comment] 2019-06-07 20:43
Thank you a lot for help. One more question: `conda` is not recognized/found before I call `source...`. Is this expected or I have to add `conda` path to the PATH variable?

**Comment by xylar** [comment] 2019-06-07 20:57
@antonio-rodriges to get `conda`, you should be sourcing a file in `etc/profile.d`.  For example, for me that's:
```
source /home/xylar/miniconda3/etc/profile.d/conda.sh
```
I'd guess by analogy that would be:
```
source /opt/anaconda/etc/profile.d/conda.sh
```
for you but you'll need to track that down.  Then, you still need to activate an environment to get python or anything else.  `conda activate` without an environment will get you the "base" environment.  But as I mentioned in another discussion, that's not really a good place to be working.  It's best to create one or more other virtual environments and treat them as "disposable" and relatively easy to rebuild as you need.  It's often better to throw an environment away and start from scratch than try to upgrade it.  But that's a long way from your question, sorry...
