### ISSUE TITLE
PROJ: proj_create_from_database: Cannot find proj.db

### ISSUE THREAD

**Issue by nlraley** [conda-forge/proj.4-feedstock#74] opened 2020-03-11 20:42 UTC
Issue:
I am attempting to run gdal.Translate after installing gdal and rasterio from conda-forge.  During the process I receive several errors regarding:
PROJ: proj_create_from_database: Cannot find proj.db
<br/>
Environment (<code>conda list</code>):
<details>

```
(GDAL) PS C:\ProgramData\Anaconda3\envs\GDAL> conda list                                                                              # packages in environment at C:\ProgramData\Anaconda3\envs\GDAL:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
boost-cpp                 1.72.0               h0caebb8_0    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py38h32f6830_1    conda-forge
cfitsio                   3.470                hfa6e2cd_2    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.68.0               h4496350_0    conda-forge
expat                     2.2.9                he025d50_2    conda-forge
freetype                  2.10.0               h563cfd7_1    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.0.4            py38h2fee047_1    conda-forge
geos                      3.8.0                he025d50_1    conda-forge
geotiff                   1.5.1                h58edbdd_9    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3          py38hc0c2ac7_1002    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.5          nompi_ha405e13_1104    conda-forge
icu                       64.2                 he025d50_1    conda-forge
intel-openmp              2020.0                      166
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            hf7dc31f_1005    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   3.0.4                hd7a9a0e_1    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libnetcdf                 4.7.3           nompi_hc957ea6_101    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     12.2                 h795e76a_0    conda-forge
libspatialite             4.3.0a            hed33574_1035    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h21b02b4_3    conda-forge
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mkl                       2020.0                      166
msys2-conda-epoch         20160418                      1
numpy                     1.18.1           py38hc71023c_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
poppler                   0.67.0               h1707e21_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 hd6b8478_0    conda-forge
proj                      6.3.1                ha7a8c7b_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
python                    3.8.2           h5fd99cc_4_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
rasterio                  1.1.3            py38h2617b1b_0    conda-forge
setuptools                46.0.0           py38h32f6830_2    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tbb                       2018.0.5             he980bc4_0    conda-forge
tiledb                    1.7.0                hffbbd95_2    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                     py_1    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                hd8a0e53_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(GDAL) PS C:\ProgramData\Anaconda3\envs\GDAL> conda info                                                                              
     active environment : GDAL
    active env location : C:\ProgramData\Anaconda3\envs\GDAL
            shell level : 2
       user config file : C:\Users\opsNathanRaley\.condarc
 populated config files : C:\Users\opsNathanRaley\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=9.2
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\opsNathanRaley\.conda\pkgs
                          C:\Users\opsNathanRaley\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\opsNathanRaley\.conda\envs
                          C:\Users\opsNathanRaley\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

(GDAL) PS C:\ProgramData\Anaconda3\envs\GDAL> 

```
</details>

**Comment by xylar** [comment] 2020-03-11 20:52
@nlraley, I won't be much help because I don't speak Windows.

Under unix, this happens because the `$PROJ_LIB` environment variable isn't set.  This could happen if the environment wasn't activated in a way that calls the script that sets this variable (i.e. if `conda activate <env_name>` wasn't called).  I'm not sure what the equivalent process in Windows looks like but could it be that you're setting up your environment in another way?

Hopefully others with Windows knowledge can chime in.

**Comment by nlraley** [comment] 2020-03-11 21:07
I am setting up the environment the same way, but when I list out the environment variables, it is clearly missing the PROJ_LIB in there.  Any ideas how to add it?

**Comment by xylar** [comment] 2020-03-11 22:16
@nlraley, if you call `conda activate <env_name>`, it should automatically be"calling" (I guess that's Windows for "sourcing") this script: 
```
call C:\ProgramData\Anaconda3\envs\GDAL\etc\conda\activate.d\proj4-activate.bat
```
That's where the environment variable gets set.  Can you verify that the script exists and that the environment variable gets set if you call it yourself with the `call` command?  If not, we need to figure out why not.  If so, we need to figure out why it's not getting called when you activate the environment.

**Comment by xylar** [comment] 2020-03-12 07:33
@nlraley, I just tested out on my Windows virtual machine after getting myself set up again.

First, I launched `Anaconda Prompt` from the `Anaconda3 (64-bit` folder in what I assume is still called the start-up menu.  (Did I mention I don't use Windows much?)

From the prompt:
```
> conda update -y conda
> conda create -y -n test proj
> conda activate test
> set PROJ
PROJ_LIB=C:\Users\xylar\Miniconda3\envs\test\Library\share\proj
PROJ_NETWORK=ON
> echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
500000.00       4427757.22
```

So everything is working great for me!  Could you let me know what you might be doing differently?

Some details for reference:

Environment (<code>conda list</code>):
<details>

```
> conda list
# packages in environment at C:\Users\xylar\Miniconda3\envs\test:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.11.28           hecc5488_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h21b02b4_3    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
openssl                   1.1.1d               hfa6e2cd_0    conda-forge
proj                      7.0.0                hfe17d32_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                hd8a0e53_1    conda-forge
```
</details>

Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
>conda info

     active environment : test
    active env location : C:\Users\xylar\Miniconda3\envs\test
            shell level : 2
       user config file : C:\Users\xylar\.condarc
 populated config files : C:\Users\xylar\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\Users\xylar\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\xylar\Miniconda3\pkgs
                          C:\Users\xylar\.conda\pkgs
                          C:\Users\xylar\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\xylar\Miniconda3\envs
                          C:\Users\xylar\.conda\envs
                          C:\Users\xylar\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.23.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by xylar** [comment] 2020-03-12 07:37
@nlraley, I just noticed that you're using `proj` 6.3.1 instead of 7.0.0, but I tested that too with the same procedure (but `proj=6.3.1` in the `conda create` command) and it worked fine, too.

**Comment by nlraley** [comment] 2020-03-12 18:17
The script exists, and after running it manually I don't see the path listed when I run conda info -s.

**Comment by xylar** [comment] 2020-03-12 19:23
@nlraley, I'd like to help more but I'm afraid what you've given me isn't much to work with.  Can you reproduce the process that worked for me?
```
> conda update -y conda
> conda create -y -n test proj
> conda activate test
> echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
```

How did you create your `GDAL` envrionment?  What steps can I use to recreate it as you do?  Could you try to recreate it with a `conda create` statement like I have above?

When you activate your `GDAL` environment, exactly what steps do you take?  When you're in your `GDAL` environment, what does `set PROJ` show?  (This should show `PROJ_LIB=C:\...` if things are set up properly).

As things stand now, I can't reproduce the error you're seeing.

**Comment by xylar** [comment] 2020-05-02 10:09
@nlraley, I'm going to close this for now.  Please re-open if you are able to provide more info on the problem.

**Closed as completed by xylar** 2020-05-02 10:09 UTC
